name: 'Yarn install'
description: 'Runs setup node + cache + yarn install'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      id: setup-node
      with:
        node-version-file: 'package.json'
        check-latest: true
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/yarn.lock', 'patches/*.patch') }}
    - name: Install Yarn dependencies
      run: |
        # Deals with yarn (v1) install flakiness
        yarn || yarn --network-concurrency 1
        # Another install flakiness fix (at least in yarn v1 with node 20)
        # yarn postinstall isn't always run (?!) so we run it manually
        yarn postinstall
      shell: bash
    - name: Fail if someone forgot to commit "yarn.lock"
      run: git diff --exit-code
      shell: bash
