queue_rules:
  - name: default
    conditions:
      # Conditions to get the queued pull request merged (on top of the branch protection rules from GitHub)
      - '-merged'

pull_request_rules:
  - name: Automatically merge on CI success and code review
    conditions:
      # Add this label when you are ready to automerge the pull request.
      - 'label=automerge'
      # Exclude drafts
      - '-draft'
      # At least one approval required
      - '#approved-reviews-by>=1'
      # Only enable this when the pull request is being merged into main
      - 'base=main'
    actions:
      queue:
        # Updates with latest from main, then merges once CI passes
        name: default
        method: squash
        commit_message_template: "{{ title }} (#{{ number }})\n\n{{ body }}"
      delete_head_branch:
        force: False
