files:
  - source: /packages/mobile/locales/base/*.json
    translation: /packages/mobile/locales/%locale%/%original_file_name%
  - source: /packages/mobile/ios/celo/Base.lproj/InfoPlist.strings
    translation: /packages/mobile/ios/celo/%osx_code%/%original_file_name%
  - source: /packages/cloud-functions/locales/en.json
    translation: /packages/cloud-functions/locales/%two_letters_code%.json
