pull_request_title: 'chore(l10n): update translations from Crowdin'
files:
  - source: /locales/base/*.json
    translation: /locales/%locale%/%original_file_name%
    type: i18next_json
  - source: /ios/MobileStack/Base.lproj/InfoPlist.strings
    translation: /ios/MobileStack/%osx_code%/%original_file_name%
