// Supported local currency codes
// Please keep it sorted alphabetically
export enum LocalCurrencyCode {
  AUD = 'AUD',
  BRL = 'BRL',
  CAD = 'CAD',
  CNY = 'CNY',
  COP = 'COP',
  CVE = 'CVE',
  EUR = 'EUR',
  GBP = 'GBP',
  GHS = 'GHS',
  GMD = 'GMD',
  GNF = 'GNF',
  INR = 'INR',
  KES = 'KES',
  LRD = 'LRD',
  MXN = 'MXN',
  NGN = 'NGN',
  PHP = 'PHP',
  PLN = 'PLN',
  RUB = 'RUB',
  RWF = 'RWF',
  SLL = 'SLL',
  TRY = 'TRY',
  TZS = 'TZS',
  UAH = 'UAH',
  UGX = 'UGX',
  USD = 'USD',
  XOF = 'XOF',
  XAF = 'XAF',
  ZAR = 'ZAR',
  ZMW = 'ZMW',
}

export enum LocalCurrencySymbol {
  AUD = 'A$',
  BRL = 'R$',
  CAD = '$',
  CNY = '¥',
  COP = '$',
  CVE = '$',
  EUR = '€',
  GBP = '£',
  GHS = 'GH₵',
  GMD = 'D',
  GNF = 'FG',
  INR = '₹',
  KES = 'KSh',
  LRD = 'L$',
  MXN = '$',
  NGN = '₦',
  PHP = '₱',
  PLN = 'zł',
  RUB = '₽',
  RWF = 'FRw',
  SLL = 'Le',
  TRY = '₺',
  TZS = 'TSh',
  UAH = '₴',
  UGX = 'USh',
  USD = '$',
  XAF = 'FCFA',
  XOF = 'CFA',
  ZAR = 'R',
  ZMW = 'ZK',
}

export const LOCAL_CURRENCY_CODES = Object.values(LocalCurrencyCode)
