// Supported local currency codes
// Please keep it sorted alphabetically
export enum LocalCurrencyCode {
  AUD = 'AUD',
  BRL = 'BRL',
  CAD = 'CAD',
  CNY = 'CNY',
  COP = 'COP',
  CVE = 'CVE',
  EUR = 'EUR',
  GBP = 'GBP',
  GHS = 'GHS',
  GNF = 'GNF',
  INR = 'INR',
  KES = 'KES',
  LRD = 'LRD',
  MXN = 'MXN',
  MYS = 'MYS',
  NGN = 'NGN',
  PHP = 'PHP',
  PLN = 'PLN',
  RUB = 'RUB',
  RWF = 'RWF',
  SGP = 'SGP',
  SLL = 'SLL',
  THI = 'THI',
  TRY = 'TRY',
  TWN = 'TWN',
  UAH = 'UAH',
  UGX = 'UGX',
  USD = 'USD',
  VNM = 'VNM',
  XAF = 'XAF',
  XOF = 'XOF',
  ZAR = 'ZAR',
}

export enum LocalCurrencySymbol {
  AUD = 'A$',
  BRL = 'R$',
  CAD = '$',
  CNY = '¥',
  COP = '$',
  CVE = '$',
  EUR = '€',
  GBP = '£',
  GHS = 'GH₵',
  GNF = 'FG',
  INR = '₹',
  KES = 'KSh',
  LRD = 'L$',
  MXN = '$',
  MYS = 'RM',
  NGN = '₦',
  PHP = '₱',
  PLN = 'zł',
  RUB = '₽',
  RWF = 'FRw',
  SGP = 'S$',
  SLL = 'Le',
  THI = '฿',
  TRY = '₺',
  TWN = 'NT$',
  UAH = '₴',
  UGX = 'USh',
  USD = '$',
  VNM = '₫',
  XAF = 'FCFA',
  XOF = 'CFA',
  ZAR = 'R',
}

export const LOCAL_CURRENCY_CODES = Object.values(LocalCurrencyCode)
