/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20'
export * as factories from './factories'
export { IERC20__factory } from './factories/IERC20__factory'
