// TODO: import this from @divvy/mobile
export type SupportedProtocol =
  | 'beefy'
  | 'tether'
  | 'somm'
  | 'celo'
  | 'aerodrome'
  | 'velodrome'
  | 'vana'
  | 'curve'
  | 'farcaster'
  | 'mento'
  | 'yearn'
  | 'fonbnk'
  | 'offchainlabs'
  | 'euler'
  | 'ubeswap'
