export const APP_NAME = 'Valora'
export const WEB_LINK = 'https://valora.xyz/'
export const CELO_FAUCET_LINK = 'https://celo.org/app'
export const CELO_TERMS_LINK = 'https://celo.org/terms'
export const TOS_LINK = 'https://valora.xyz/terms'
export const PRIVACY_LINK = 'https://valora.xyz/privacy'
export const FAQ_LINK = 'https://valora.xyz/faq'
export const HELP_LINK = 'https://valora.xyz/support'
export const FUNDING_LINK = 'https://valora.xyz/fund-wallet'
export const CELO_REWARDS_LINK = 'https://celo.org/celo-rewards-education'
export const FORUM_LINK = 'https://forum.celo.org/c/valora/8'
export const SUPERCHARGE_LEARN_MORE = 'https://valora.xyz/support/supercharge-learn-more'
export const INVITE_REWARDS_LEARN_MORE = 'https://valora.xyz/support/invite-rewards-learn-more'
export const DAPPS_LEARN_MORE = 'https://valora.xyz/support/dapps-learn-more'
export const SWAP_LEARN_MORE = 'https://valora.xyz/support/swap-learn-more'
export const TRANSACTION_FEES_LEARN_MORE = 'https://valora.xyz/support/transaction-fees-learn-more'
export const INVITE_REWARDS_NFTS_LEARN_MORE =
  'https://valora.xyz/support/invite-rewards-nfts-learn-more'
export const INVITE_REWARDS_STABLETOKEN_LEARN_MORE =
  'https://valora.xyz/support/invite-rewards-stabletoken-learn-more'
export const EARN_STABLECOINS_LEARN_MORE = 'https://valora.xyz/stablecoin-earn'
