name: Automerge Crowdin

on:
  workflow_dispatch:
  # At 02:00 (UTC) daily
  # https://crontab.guru/#0_2_*_*_*
  # 1 hour before the nightly build
  schedule:
    - cron: '0 2 * * *'

jobs:
  automerge-crowdin-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Google Secrets
        id: google-secrets
        uses: google-github-actions/get-secretmanager-secrets@v1.0.1
        with:
          secrets: |-
            VALORA_BOT_TOKEN:projects/1027349420744/secrets/VALORA_BOT_TOKEN
          credentials: ${{ secrets.MAINNET_SERVICE_ACCOUNT_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/github-script@v5
        with:
          github-token: ${{ steps.google-secrets.outputs.VALORA_BOT_TOKEN }}
          script: |
            const script = require('.github/scripts/automergeCrowdinPr.js')
            await script({github, context, core})
