name: Automerge translations

on:
  workflow_dispatch:
  # Hourly on workdays
  # https://crontab.guru/#0_*_*_*_1-5
  schedule:
    - cron: '0 * * * 1-5'

jobs:
  automerge-translation-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          project_id: celo-mobile-mainnet
          credentials_json: ${{ secrets.MAINNET_SERVICE_ACCOUNT_KEY }}
      - name: Google Secrets
        id: google-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2.1.3
        with:
          secrets: |-
            VALORA_BOT_TOKEN:projects/1027349420744/secrets/VALORA_BOT_TOKEN
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.google-secrets.outputs.VALORA_BOT_TOKEN }}
          script: |
            const script = require('.github/scripts/automergeTranslationPrs.js')
            await script({github, context, core})
