# This workflow is responsible for generating Valora's IPA
# and APK files for Alfajores and Mainnet and upload them
# to TestFlight and Google Play.
name: Production

on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: 'Release Branch'
        required: true

jobs:
  ios:
    uses: ./.github/workflows/fastlane-ios.yml
    with:
      branch: ${{ github.event.inputs.release_branch_name }}
      lanes: '["alfajores", "mainnet"]'
    secrets:
      gcp-service-account-key: ${{ secrets.GCP_MAINNET_RELEASE_AUTOMATION_SERVICE_ACCOUNT_KEY }}

  android:
    uses: ./.github/workflows/fastlane-android.yml
    with:
      branch: ${{ github.event.inputs.release_branch_name }}
      lanes: '["alfajores", "mainnet"]'
    secrets:
      gcp-service-account-key: ${{ secrets.GCP_MAINNET_RELEASE_AUTOMATION_SERVICE_ACCOUNT_KEY }}
