name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger:
    name: Trigger
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TRIGGER_SSH_PRIVATE_KEY }}
      - run: |
          rm -rf .git/
          cd ..
          git clone git@github.com:valora-inc/wallet-release-reflection.git
          mv wallet/ wallet-release-reflection/
          cd wallet-release-reflection
          git add -A
          git commit -m "New Changes"
          git push
