name: Semantic PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  merge_group:

jobs:
  semantic-pr-title:
    name: Semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # This action can only be run in `pull_request_target` and `pull_request` events
        # Workaround from https://github.com/amannn/action-semantic-pull-request/issues/236#issuecomment-1695654373
        if: ${{ github.event_name != 'merge_group' }}
